packages:
  - apps/*

catalogs:
  monorepo:
    "turbo": "^2.5.3"
    "pnpm": "^10.11.0"
    "@antfu/ni": "^23.3.1"
  base:
    "@clack/prompts": ^0.10.1
    "bumpp": "^10.1.1"
    "esno": "^4.8.0"
    "tsdown": "^0.11.12"
    "typescript": "^5.8.3"
    "vite": "^6.3.5"
    "vitest": "^3.1.4"
    "pluralize": "^8.0.0"
    "ts-morph": "^26.0.0"
  vscode:
    "vscode-ext-gen": "^1.0.2"
    "@vscode/vsce": "^3.4.1"
    "reactive-vscode": "^0.2.17"
  type:
    "@types/node": "^22.15.19"
    "@types/pluralize": "^0.0.33"
    "@types/vscode": "^1.97.0"
  lint:
    "@wisemen/eslint-config-vue": "^1.5.0"
    "eslint": "^9.27.0"
